### ISSUE TITLE
mtl 2.2.x means this cannot cannot be built

### ISSUE THREAD

**Issue by peti** [nikita-volkov/mtl-prelude#1]
Do you realize that no release version of GHC can be used to build non-trivial software that depends on this package? The latest GHC, 7.8.3, ships transformers 0.3.x, i.e. this is a core package that cannot be updated. Every build that depends on the `ghc` library (such as every package that uses `doctest`) must link transformers 0.3.x and as such cannot link your library. 

IMHO, it would be great if your package could support both mtl 2.1.x and 2.2.x i.e. by adding appropriate CPP conditionals.

**Comment by nikita-volkov** [comment]
> this is a core package that cannot be updated

You're confused. I'm on 7.8.3 myself. Yes, it comes packaged with some basic libraries, but that doesn't mean, that you can't install their newer versions in a per user package database or a sandbox.

As a testimony, here's [a Travis build](https://travis-ci.org/nikita-volkov/mtl-prelude/builds/38698260), which successfully installs this library against GHC 7.6 and 7.8.

**Comment by peti** [comment]
You may want to re-read my message. Try adding a dependency `ghc == 7.8.3` to your library's cabal file and see what happens then.

**Comment by peti** [comment]
Just in case ... here is the patch: 

```
--- a/mtl-prelude.cabal
+++ b/mtl-prelude.cabal
@@ -49,7 +49,8 @@ library
     MTLPrelude
   build-depends:
     transformers == 0.4.*,
-    mtl == 2.2.*
+    mtl == 2.2.*,
+    ghc == 7.8.3
   default-extensions:
     Arrows, BangPatterns, ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable, DeriveFunctor, DeriveGeneric, EmptyDataDecls, FlexibleContexts, FlexibleInstances, FunctionalDependencies, GADTs, GeneralizedNewtypeDeriving, ImpredicativeTypes, LambdaCase, LiberalTypeSynonyms, MagicHash, MultiParamTypeClasses, MultiWayIf, NoImplicitPrelude, NoMonomorphismRestriction, OverloadedStrings, PatternGuards, ParallelListComp, QuasiQuotes, RankNTypes, RecordWildCards, ScopedTypeVariables, StandaloneDeriving, TemplateHaskell, TupleSections, TypeFamilies, TypeOperators, UnboxedTuples
   default-language:
```

Now run `cabal configure`.

**Comment by nikita-volkov** [comment]
Okay. I've published an update. You're interested in version 1.0.0.
